### ISSUE TITLE
Pause control isn't working when playing video in Picture-in-Picture mode

### ISSUE THREAD

**Issue by reginabally** [Automattic/pocket-casts-ios#742] opened 2023-02-25 01:10 UTC
Reported in 5989344-zd-woothemes

### Expected behavior

I expect when I press the Pause command on the video player when playing it in Picture-in-Picture mode, and the video will pause.

### Actual behavior

> When doing a video podcast and you activate PiP, the pause icon activates twice, meaning it just pauses then resumes. 

### Steps to reproduce the behavior

1. Play a video episode in the app
2. Activates the Picture-in-Picture mode
3. Tap the Pause command
4. Notice the video pauses for less than a second and resumes.

#### Video recording

https://user-images.githubusercontent.com/40906847/221327668-098e9415-b695-4d97-b92f-6cc44848e21c.MP4

##### Tested on iPhone 11, iOS 16.3.1, Pocket Casts 7.32

**Comment by joashrajin** [comment] 2023-02-28 13:56
Reported in the beta Slack too: https://pocketcastsbeta.slack.com/archives/C0GKZ8J4A/p1677592426694139

**Comment by emilylaguna** [comment] 2023-02-28 14:58
I am closing this since this is caused by the same issue as https://github.com/Automattic/pocket-casts-ios/issues/735 and was fixed by https://github.com/Automattic/pocket-casts-ios/pull/739

The fix for this has been released in both the latest App Store (7.32.1) and TestFlight (7.33.0.1) versions.

**Closed as completed by emilylaguna** 2023-02-28 14:58 UTC
Labels: [Type] Bug
