### ISSUE TITLE
Setting a skip last value causes autoplay to stop working

### ISSUE THREAD

**Issue by geekygecko** [Automattic/pocket-casts-ios#2019] opened 2024-08-12 01:48 UTC
### Description

This issue was [reported on the forums](https://forums.pocketcasts.com/forums/topic/autoplay-not-working-when-skip-last/?view=all). If you set a skip last value for a podcast when you finish the episode the autoplay feature doesn't work.

### Step-by-step reproduction instructions

1. Open a podcast
2. Tap the setting cog
3. Change the Skip Last to 30 seconds
4. Clear the Up Next
5. Play an episode

When the episode reaches 30 seconds before its end, it should finish and move on to the next episode. 

### Screenshots or screen recording

https://github.com/user-attachments/assets/705cae7a-b226-4fc7-b2f6-2f130be40037

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

iPhone 12 Pro, iOS 17.5.1, Pocket Casts 7.70.0.2

**Comment by SergioEstevao** [comment] 2024-08-12 15:52
@geekygecko I had a look into this and on my tests I initially could reproduce it and found that for some reason the episode and podcast recorded on our local DB being used were not linked. So the setting didn't have any effect.
After I deleted the app and signed in again all started to work again.
Are you still seeing the issue in your account?

**Comment by geekygecko** [comment] 2024-08-13 06:52
I can still reproduce this issue on 7.70. I signed out and reinstalled the app, and I could still repeat it.

**Comment by geekygecko** [comment] 2024-08-14 00:23
> Does it also fails the skip at start?

No, it only happens when I set the skip last.

> And does it happens to all of your podcasts?

I might not test all of them as I have 150 podcasts, I tested with the following and it happens with all of them:

[The Squiz Today](https://pca.st/Tu5j)
[The Party Room](https://pca.st/partyroom)
[Head Game](https://pca.st/6puyl8cq)

Can anyone else on the iOS team reproduce it?

**Comment by rviljoen** [comment] 2024-08-14 11:04
This issue is present on all podcasts. The problem is that the logic for checking for autoplay is called here in `playerDidFinishPlayingEpisode()` :

https://github.com/Automattic/pocket-casts-ios/blob/8725667669e818aee1036bb149ab04ed40f279ad/podcasts/PlaybackManager.swift#L975-L977

but this function is only called if the player reaches the end of the file and notifies us via `NSNotification.Name.AVPlayerItemDidPlayToEndTime`

https://github.com/Automattic/pocket-casts-ios/blob/8725667669e818aee1036bb149ab04ed40f279ad/podcasts/DefaultPlayer.swift#L625
https://github.com/Automattic/pocket-casts-ios/blob/8725667669e818aee1036bb149ab04ed40f279ad/podcasts/DefaultPlayer.swift#L639

With the skip last x seconds logic, the player never reaches the end of the file and hence the `playerDidFinishPlayingEpisode` logic is never called. Instead, the episode is marked as complete here:

https://github.com/Automattic/pocket-casts-ios/blob/8725667669e818aee1036bb149ab04ed40f279ad/podcasts/PlaybackManager.swift#L1354-L1358

`EpisodeManager.markAsPlayed` in turn calls `PlaybackManager.shared.removeIfPlayingOrQueued`. The logic here only checks for autoplaying if the queue has episodes and not when the queue is empty, as is the case for the autoplay setting:

https://github.com/Automattic/pocket-casts-ios/blob/8725667669e818aee1036bb149ab04ed40f279ad/podcasts/PlaybackManager.swift#L546-L555

We just need to add `autoPlayIfNeeded()` to this method.

As an aside, this bug is also present when marking episodes as complete from the mini player or full screen player shelf icon.

**Comment by SergioEstevao** [comment] 2024-08-14 11:50
Great investigation @rviljoen ! 

I misunderstand the initial problem I thought the issue was that skip last was not working! 

I will put a PR up to fix this!

**Comment by rviljoen** [comment] 2024-08-14 12:01
@SergioEstevao All good! When you make the change, it is worth validating my thinking about where to put the call to `autoPlayIfNeeded()`. Initially I thought maybe where we do the skip outro check, but then we need to do the same where we mark episode as played in mini player, player shelf, etc leading to duplicate code. Next idea was in `EpisodeManager.markAsPlayed`, but `autoPlayIfNeeded` is a private method on `PlaybackManager`. That lead me to `removeIfPlayingOrQueued`, which seems like a good place because we also auto play next in the queue from there, so the logic should be similar.

**Closed as completed** 2024-08-16 14:18 UTC
Labels: [Type] Bug, playback
