### ISSUE TITLE
Notifications: Stops working after a migration to a new device

### ISSUE THREAD

**Issue by joashrajin** [Automattic/pocket-casts-ios#1198] opened 2023-11-02 11:04 UTC
### Description

We've had quite a number of users report that notifications aren't working after they have migrated to a new Apple device. 

Despite notifications being enabled in Pocket Casts and iOS itself, the notifications never work. The only solution is to reinstall the app which is not a great workaround since users will lose all of their custom settings + downloads. several

### Step-by-step reproduction instructions

1. Transfer your data from an old iPhone with notifications enabled to a new iPhone
2. Confirm on the new device that notifications are enabled in iOS and Pocket Casts
3. Notice the notifications do not come through

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

App Version: 7.50, Device: iPhone16,2, OS: 17.1

**Comment by joashrajin** [comment] 2023-11-02 11:06
7246095-zd-a8c

**Comment by joashrajin** [comment] 2023-11-02 11:07
6494345-zd-a8c

**Comment by joashrajin** [comment] 2023-11-02 11:07
6210066-zd-a8c

**Comment by joashrajin** [comment] 2023-11-02 11:08
6047822-zd-a8c

**Comment by joashrajin** [comment] 2023-11-02 11:08
More reports in this thread: https://forums.pocketcasts.com/forums/topic/ios-not-receiving-notifications-from-pocket-casts/

**Comment by rviljoen** [comment] 2023-11-02 15:58
@joashrajin Seems to be a duplicate of #1177. I like this description better though as I don't think the issue is limited to the iPhone 15 Pro.

**Comment by joashrajin** [comment] 2023-11-02 16:02
@rviljoen good point. I'll close that issue so this one can be used instead

**Comment by joashrajin** [comment] 2023-11-02 16:03
7204541-zd-a8c

**Comment by joashrajin** [comment] 2023-11-02 16:03
7176573-zd-a8c

**Comment by rviljoen** [comment] 2023-11-02 20:29
In researching this issue, I found [another user report](https://www.reddit.com/r/pocketcasts/comments/17eu6sp/comment/k68aont/?utm_source=reddit&utm_medium=web2x&context=3) on Reddit which claims that notifications never work after transferring to a new phone or restoring from iCloud backup.

> Delete and reinstall did not help (it does fix it every time when moving to a new phone… for some reason Pocket Cast notifications never work again after a phone to phone migration or a restore from iCloud…)

**Comment by rviljoen** [comment] 2023-11-02 21:09
I have done some research on this issue and found the following. In order for a device to receive push notifications, it must register via `UIApplication.shared.registerForRemoteNotifications()` and receive a unique device token. The process is documented [here](https://developer.apple.com/documentation/uikit/uiapplication/1623078-registerforremotenotifications).

This token is unique per device, so after setting up a new device we need to call it at least once to get the device specific token. The only place in Pocket Casts where we make this call is here:
https://github.com/Automattic/pocket-casts-ios/blob/ae46fed9d26748f106c04db3cc041851fb2ef503/podcasts/NotificationsHelper.swift#L37

We do call this method on app launch, if push notifications are enabled, which is a good start:
https://github.com/Automattic/pocket-casts-ios/blob/ae46fed9d26748f106c04db3cc041851fb2ef503/podcasts/NotificationsHelper.swift#L31-L35

I believe the problem lies in this part of `registerForPushNotifications()`

https://github.com/Automattic/pocket-casts-ios/blob/ae46fed9d26748f106c04db3cc041851fb2ef503/podcasts/NotificationsHelper.swift#L54-L68

We check if notifications access is `notDetermined`. If yes, then we ask the user for permission and if granted, only then do we fetch the token. I think the problem is that with a phone restore or migration, the permission which was granted to the app on the old device is transferred by iOS, so `settings.authorizationStatus` will be `authorized` if notifications were previously enabled (values as defined in `UNAuthorizationStatus`)

```
    // The user has not yet made a choice regarding whether the application may post user notifications.
    case notDetermined = 0
    // The application is not authorized to post user notifications.
    case denied = 1
    // The application is authorized to post user notifications.
    case authorized = 2
    // The application is authorized to post non-interruptive user notifications.
    @available(iOS 12.0, *)
    case provisional = 3
```
If this is indeed the case, then we return early from this function and never register the new phone to get a device token.

In addition to the problem with phone migration or restores, I think another issue is present in the existing code on a clean install. If we ask the user for notification permission and she declines, then the token will not be fetched. If the user then manually changes the permission in iOS settings (from `denied` to `authorized`), then the code will still exit early and never fetch a new token. The only way to get status to `notDetermined` is to reinstall the app.

I think the solution is to move `UIApplication.shared.registerForRemoteNotifications()` outside of the request for authorisation logic and to always fetch a token on app launch. If the user declines the request, then notifications will be delivered silently, so there should be no impact in this case

> If you want your app’s remote notifications to display alerts, play sounds, or perform other user-facing actions, you must request authorization to do so using the [requestAuthorization(options:completionHandler:)](https://developer.apple.com/documentation/usernotifications/unusernotificationcenter/1649527-requestauthorization) method of [UNUserNotificationCenter](https://developer.apple.com/documentation/usernotifications/unusernotificationcenter). If you do not request and receive authorization for your app's interactions, the system delivers all remote notifications to your app silently.

I'm a little bit out of my depth here, so keen to here from @emilylaguna or @leandroalonso before attempting a fix.

**Comment by rviljoen** [comment] 2023-11-02 21:16
@emilylaguna Just looking at the commit history now, I think the bug may have been introduced in https://github.com/Automattic/pocket-casts-ios/commit/960d9a9024c7fec55b1fe61f99a5a2c0020472ff

Let me know what you think.

**Comment by rviljoen** [comment] 2023-11-03 07:21
After looking into this some more, I am fairly sure that this bug was introduced by https://github.com/Automattic/pocket-casts-ios/commit/960d9a9024c7fec55b1fe61f99a5a2c0020472ff. Reading through the documentation again, it suggests that `requestAuthorization(options:completionHandler:)` may be called multiple time (like we did upon app launch in the old code), but a cached response will be returned:

>The first time your app ever calls the method, the system prompts the user to authorize the requested interactions. The user may grant or deny authorization, and the system stores the user’s response so that subsequent calls to this method do not prompt the user again. After determining the authorization status, the user notification center object executes the block in the completionHandler parameter. Use that block to make any adjustments to your app’s behavior. For example, if authorization was denied, you might notify a remote notification server not to send notifications to the user’s device.

I think the old code should also be enhanced to inform the Pocket Casts notification server if this method returns a declined status. This will cater for the situation where the user initially accepts the notifications prompt, but subsequently changes the permission in iOS user settings.

**Comment by joashrajin** [comment] 2023-11-06 11:19
+1 in 7264149-zd-a8c

**Comment by leandroalonso** [comment] 2023-11-07 14:21
> I think the old code should also be enhanced to inform the Pocket Casts notification server if this method returns a declined status. This will cater for the situation where the user initially accepts the notifications prompt, but subsequently changes the permission in iOS user settings.

I agree.

And it does look like that change might have introduced this bug given I don't remember receiving those complaints during the iPhone 13-14 migration.

**Comment by erricgunawan** [comment] 2023-11-22 01:17
2-star iOS app review:

> ... more time fixing the non-existent notifications, now going on two weeks.
>
> Update: November now and while notifications were back for about ten days they are completely gone again. Plus episodes are not available even upon opening the app for more than 30 minutes after they appear in other podcast apps. 
>
> ... Notifications weren’t working for about five days recently, then they all came in over about three hours.

**Comment by rviljoen** [comment] 2023-11-22 09:35
Hi @erricgunawan - reading through the user feedback, I think there could be 3 separate issues here all related to notifications:

1. Notifications completely stop working after migration to new device (logged as this issue)
2. Delay between receiving the notification and the episode showing as available in the app
3. On non-migrated devices, notifications sporadically stop working and then return 

For 1) we have already determined that this is a bug in the app which was introduced with change https://github.com/Automattic/pocket-casts-ios/commit/960d9a9024c7fec55b1fe61f99a5a2c0020472ff. For 2) and 3), I suspect that these may be server side issues on the Notifications server.

I think it's a good idea to log 2) and 3) as separate issues so that the right team can look at them.

**Comment by erricgunawan** [comment] 2023-11-23 02:32
@rviljoen Yes, I believe there is another ongoing work to investigate the delay in notification, so thanks for bringing that up!

**Comment by csegyud** [comment] 2023-12-13 15:20
Hi, the same issue happenes on android. PC: V7. 52 (8168) Android: 13 (miui 14). Do you have a separate issue for the android notification problem too? Thanks.

**Comment by leandroalonso** [comment] 2023-12-13 17:18
@csegyud I don't think so, cc @Automattic/pocket-casts-android

**Comment by joashrajin** [comment] 2023-12-14 08:06
> I’m not receiving any notifications since changing my phone (an iPhone) and restoring from backup.

7430248-zd-a8c

**Comment by igotdes** [comment] 2024-01-18 06:08
#7532647-zen

**Comment by schaphil** [comment] 2024-03-01 12:46
Hey Guys, Is there any news here? I would like to receive notifications again 🙂

**Comment by rviljoen** [comment] 2024-03-11 16:27
@schaphil Fix is currently being tested in TestFlight v7.59, so should be in the production release soon 🥳

**Comment by rviljoen** [comment] 2024-03-18 20:03
@schaphil fix is now live in the App Store. 

@joashrajin I think this one can now be closed.

**Comment by petercockroach** [comment] 2024-03-19 06:31
Verified - I've had this longstanding bug and today it started working again after updating the app. Thanks for the fix!

**Closed as completed** 2024-03-19 17:08 UTC
