### ISSUE TITLE
Podcasts page scrolls slightly horizontal 

### ISSUE THREAD

**Issue by azollafox** [Automattic/pocket-casts-ios#1930] opened 2024-07-23 17:46 UTC
### Description

When scrolling down in the list of podcasts on the podcast page it is possible to scroll horizontally a bit as well

### Step-by-step reproduction instructions

1. Open Podcast Page
2. Scroll down and move finger right to left as well

I am able to inconsistently reproduce on my iPhone SE, Pocket Casts 7.67

### Screenshots or screen recording

https://d.pr/v/gcawUs

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Pocket Casts v7.68
Device: iPhone13,3
OS: 17.5.1

**Comment by leandroalonso** [comment] 2024-07-23 17:48
cc @SergioEstevao (I believe this was reported before but I couldn't find the issue/thread — and if my memory is not failing it was in a small screen device).

Edit: [found it](https://github.com/Automattic/pocket-casts-ios/issues/1799#issuecomment-2160844456).

**Comment by rviljoen** [comment] 2024-07-23 18:03
I sporadically see this on iPhone 14 Pro as well:

![image](https://github.com/user-attachments/assets/33ebbddf-01c7-4f4f-89f9-6fb6ac2085f7)

**Comment by joashrajin** [comment] 2024-07-24 11:21
+1 at 8516326-zd-a8c


https://github.com/user-attachments/assets/9d2ef8da-2f0a-4d05-9f4e-0c7123c2a75f

**Comment by rviljoen** [comment] 2024-07-24 15:41
@SergioEstevao I wonder if this bug may be related to this change: https://github.com/Automattic/pocket-casts-ios/commit/b7a14a6b5b537eb33f100bee4c4617c2cb72d873

When the UI is displayed correctly, then the x inset value is -16:
![image](https://github.com/user-attachments/assets/5f94e41e-68d4-4b67-912f-8f04a17ca1b6)

When the UI is incorrect, the x inset value is 0:
![image](https://github.com/user-attachments/assets/2a29f306-d56e-44d0-8536-e025a4537e80)

**Comment by SergioEstevao** [comment] 2024-07-25 10:53
Thanks @rviljoen ! I'm having a look into this today. Should have a Pr out with a fix later today.

**Comment by rviljoen** [comment] 2024-07-25 14:33
Hi @SergioEstevao - I tested the code change in https://github.com/Automattic/pocket-casts-ios/pull/1943 and can still reproduce the issue. I can now replicate it consistently by scrolling up/down/left/right quickly, and periodically releasing touch. The left margin disappears upon releasing touch after the rapid scrolls and returns as soon as you touch the screen again (PS - I also saw this behaviour under normal scrolling, but with rapid scrolling I was able to consistently reproduce it, which may be useful for you to find the bug).

https://github.com/user-attachments/assets/b913e9ae-598d-45a2-bcb7-dbc74f8ba6ee

**Comment by SergioEstevao** [comment] 2024-07-25 15:50
Thanks for testing it @rviljoen ! I will give it another look.

**Comment by bikrrr** [comment] 2024-08-04 20:09
I'm glad this is being looked at—it's been bugging me since the podcast grid update. The issue is most noticeable when there are more rows than can fit on the screen and happens in both 4-column and 3-column grid sizes. 

If I start with the grid at the bottom (so the **Search** box is visible), I just scroll up slightly and the grid will shift left. Here's my repro on an iPhone 15 Pro, iOS 17.6, and Pocket Casts 7.68:

https://github.com/user-attachments/assets/311654ea-64f5-4070-9b04-485f8bc8ff15

**Comment by rviljoen** [comment] 2024-08-04 20:44
@bikrrr This was fixed in the latest beta and should make it into the 7.69 public release 👌🏻

**Comment by rviljoen** [comment] 2024-08-06 09:15
@azollafox This was fixed via https://github.com/Automattic/pocket-casts-ios/pull/1943 and released in v7.69.

**Closed as completed** 2024-08-06 13:51 UTC
Labels: [Type] Bug
