### ISSUE TITLE
Battery Usage

### ISSUE THREAD

**Issue by pocketcasts** [Automattic/pocket-casts-ios#17] opened 2022-07-11 19:52 UTC
### User report

>Just sent a Twitter DM as well but I’m finding the app uses a ton of power. Is this expected? Was surprised to find my new iPhone 13 Pro doesn’t have that much better battery life than my aging iPhone XS, and seems Pocket Casts is the primary culprit. 
![image1](https://user-images.githubusercontent.com/7907292/140335853-b7092c8f-5d53-476d-9411-0df84f20f825.png) ![image0](https://user-images.githubusercontent.com/7907292/140335860-87de167b-b7cf-4020-9491-9c6a7d14446f.png)

### Additional info

From Chip Snyder:

I spent some time looking onto this and I have a few take-aways for this user. 

They're on `7.18.1` and they have `132` podcasts that they subscribe to. Also a few settings that stand out to me: 
> Auto Download On: yes
> Auto Download Only on Wifi: yes
> Auto Download Up Next:  yes

They have Auto-Download on but our logs don't provide insight into how many are included in the Auto-Download. We might want to add that to the meta-data if these issues persist. I wasn't familiar with the app "No Cell Coverage" but [apparently](https://discussions.apple.com/thread/7421202) this is a tool that Apple will use to help boost the signal in low connectivity cases. 

**Thoughts**
Given that they have so many podcasts and that they Auto Download I wonder if their battery is being effected by episodes downloading under cellular data. If they're downloading on a cell network (especially a poor cellular network) then they'll definitely have a greater impact on their battery life. 

With that bug fixed I'd be interested to see how their battery usage impact changes because they have all of the settings I would encourage them to use. Maybe turn off `Auto Download` for shows that they don't listen to regularly 🤷 and only download them when added to up next using `Auto Download Up Next`

----- 
# Other Research

I did some deep diving into this over the last two days so I want to document some of my findings before the week is out. 

I pulled up some of our battery stats and found a few interesting cases. Our biggest impact is while in the background which should be expected given the nature of the app.

| Average Users | Heavy Users |
| --- | --- |
| <img width="1168" src="https://user-images.githubusercontent.com/3384451/141365455-47427976-121e-470e-a71f-e8ab92d0bb1a.png"> | <img width="1168" src="https://user-images.githubusercontent.com/3384451/141365149-f91341c2-6388-4e1f-ac68-64a1329713b3.png"> |

For our average users our impact is minimal and we shouldn't worry too much IMO. We average about 1.3% of their daily battery usage which is down from the previous release. 

Our heavy users use 6.65% on average (this aligns pretty closely to my own use.) Audio is high (2.59%) but that's expected and I haven't found a way to be more efficient there yet. Processing is nearly just as high though. 

----- 

### FileLog

I believe a big contributor to the processing impact is due to the FileLog. Each time an event fires a loggable event the process is
- Open the log file
- Seek to the end
- Write the log
- Close

This kind of I/O can be expensive. A few [recommendations from Apple](https://developer.apple.com/library/archive/documentation/Performance/Conceptual/EnergyGuide-iOS/MinimizeIO.html#//apple_ref/doc/uid/TP40015243-CH42-SW1):

> Minimize data writes. Write to files only when their content has changed, and aggregate changes into a single write whenever possible. Avoid writing out an entire file if only a few bytes have changed. **If you frequently change small portions of large files, consider using a database to store the data instead.**

While streaming an episode our energy impact is on the high side.
<img width="1142" src="https://user-images.githubusercontent.com/3384451/141372276-5ef17148-d6a7-4038-9997-9174727f6980.png">

Running the same test with the file log disabled moved us back into the low category. 
<img width="1174" src="https://user-images.githubusercontent.com/3384451/141372963-72333d9f-723f-4716-9bc4-3a65c8e83d78.png">

Batching these events and/or moving them to the DB could also be a viable approach to saving us energy usage. However this needs more validation because it's not a 1 to one comparison given the network calls that happen around these screen shots with various intervals. Which raises that we might be able to batch requests as well. 

More info: #4529585-zen

**Comment by mdrockwell** [comment] 2023-08-31 13:56
[From the forum](https://forums.pocketcasts.com/forums/topic/pocket-casts-ios-battery-usage-is-much-higher-than-apple-podcasts/?view=all#post-1211):

> there is definitely something off with Pocket Casts on ios battery usage, I wrote a message with screenshots to support (via the in app support) about a month ago. (didn’t hear back)
> 
> I only use Pocket Casts to play back low bitrate MP3s of old Howard Stern radio shows , these are added directly onto my device, and then shared within the phone to Pocket Casts, I play them back, using the speaker with the screen off.Im on the latest iOS 16.4, and have an iPhone 13 Pro . you can see the battery usage in screen shots below below, in fact, my phone rarely goes under 70% battery usage on a normal day which is why I started noticing this.
> 
> (to be clear there is no Internet usage associated with my playback, even though I am connected to Wi-Fi- , and usually within about four hours. My battery will be totally drained while playing mp3s in pocket casts (and with the screen off)
> 
> I hope this will be looked into, thanks

(The images didn't attach to the message.)

**Comment by mdrockwell** [comment] 2023-08-31 13:56
[And another one from the forum](https://forums.pocketcasts.com/forums/topic/pocket-casts-ios-battery-usage-is-much-higher-than-apple-podcasts/?view=all#post-1239):

> Okay, I ran Pocket Casts for another eight days, this time with Trim Silence disabled. The result was an average of 7m 27s per percentage point, an improvement from 6m 15s. Though, still not as good as Apple Podcasts which was 10m 25s. I did have Apple Podcasts auto-download episodes during its test period.

```
Date	        App	        %	Total	Min/Percent
2023-08-04	Podcasts	32%	4:46	0:09
2023-08-05	Podcasts	24%	3:41	0:09
2023-08-07	Podcasts	20%	3:54	0:12
2023-08-08	Podcasts	18%	2:52	0:10
2023-08-09	Podcasts	17%	3:26	0:12
2023-08-10	Podcasts	28%	5:46	0:12
2023-08-11	Podcasts	20%	3:22	0:10
2023-08-12	Podcasts	37%	5:45	0:09
			              Average	0:10:25
2023-08-21	Pocket Casts	13%	1:23	0:06
2023-08-22	Pocket Casts	31%	4:05	0:08
2023-08-23	Pocket Casts	30%	3:33	0:07
2023-08-24	Pocket Casts	38%	4:10	0:07
2023-08-25	Pocket Casts	32%	4:14	0:08
2023-08-26	Pocket Casts	34%	5:13	0:09
2023-08-27	Pocket Casts	36%	5:44	0:10
2023-08-28	Pocket Casts	33%	2:44	0:05
			              Average	0:07:27
```

**Comment by bob454522** [comment] 2023-09-09 06:11
thanks for bringing this to github as a bug report, I'm the one who chimed in with the screenshots over from the PC forums-  to add another data point-

I have switched over to using evermusic app and playing the exact same content on the same phone, I do not see the issue at all

For example, currently I’ve played one hour and 30 minutes with the screen off / background audio via speaker phone speaker and my battery is still above 90%, with Pocket Casts I would be at 60% or less.

![IMG_0351](https://github.com/Automattic/pocket-casts-ios/assets/60830628/f8dd8925-e4f4-44fe-904a-7b2f9f842533)

as expected, the phone also does not get hot temperature-wise when the screen is off and I've been playing the audio for a long amount of time (as it does with pocket casts).  
while above is the screenshot / hard data I currently have, yesterday, I used evermusic to listen to about 3 to 4 hours with the screen off and my battery still had very little drain / impact.

(I do still use Pocket Casts for podcasts and will continue to, I can't comment yet if this same pocket casts battery issue exists when playing podcasts as I don't listen to them frequently, but will do so soon as a test)

**Comment by rviljoen** [comment] 2023-11-03 14:08
I made a change recently which should improve battery usage when trim silence is disabled. See https://github.com/Automattic/pocket-casts-ios/issues/1184 for more info. Currently being tested in TestFlight Build 7.51.0.0

**Comment by erricgunawan** [comment] 2023-11-04 05:15
Another report from 7240309-zen:

> The iOS app uses crazy amounts of battery (like 20% of all apps).
>
> I listen to most podcasts at 1.3x speed but surely the transcoding can’t be that inefficient? If that’s the cause can you do the transcoding in the cloud?

> The issue is not new but I feel it got worse recently perhaps with iOS 17.x. 
No volume boost. 

> App Version: 7.50
Device: iPhone15,2
OS: 17.1

Looks like there's another report here: https://github.com/Automattic/pocket-casts-ios/issues/663 (which has more replies/reports).

I wonder if they're the same and/or they can be merged or closed for duplicate.

**Comment by rviljoen** [comment] 2023-11-05 20:07
@erricgunawan In terms of the speed adjustment, all of that is handled by Apple's implementation and there is no custom Pocket Casts code involved. The same goes for volume boost. So in theory, these should not be culprits in terms of high CPU code.

Trim Silence does use custom code, which definitely adds some overhead but it should not be as significant as the user is reporting. If the user does use trim silence, please ask to disable it and see if it improves things. Then we'll know where to investigate next.

I also think that this is a duplicate of #663, but both contain some useful info so I would suggest keeping both open for now.

**Comment by rviljoen** [comment] 2023-11-05 20:10
@leandroalonso @emilylaguna In Chip's initial post he looked at some metrics for Average and Heavy Users for v7.18.1. It would be good to run the same stats for the latest version and compare, to see if there was indeed a spike after iOS 17, as the user suspects.

**Comment by erricgunawan** [comment] 2023-11-06 06:45
~Another one from 7261096-zen~

> ~I was emailing as at the moment Pocket Casts seems to be causing significant battery drain - for example see screenshot attached ~12% with 1.5 hours of listening.~
>
> ~It's not something I've kept a track of very closely but my battery life for some reason has been not great recently so just looking at things that may be contributing. This drain certainly seems higher than I might expect.~ 

<details>
  <summary>Screenshot:</summary>
  <br>
  
![image](https://github.com/Automattic/pocket-casts-ios/assets/1813857/e7238e88-c93c-445f-999a-2a1618a5c82c)
  
</details>

~Asked if they're using Trim Silence (and to disable it and see if it improves things).~

UPDATE: the report above is using Android, not iOS.

**Comment by rviljoen** [comment] 2023-11-06 07:44
@erricgunawan That last screenshot is from Android 😀

**Comment by erricgunawan** [comment] 2023-11-07 07:29
> That last screenshot is from Android 😀

🤦🏻‍♂️ I didn't realize it!

Sorry for the false report and thanks for catching it!! I'll update it.

**Comment by rviljoen** [comment] 2023-11-07 07:35
@erricgunawan No worries! There are enough iOS reports as well to warrant further investigation. The fact that it happens on Android as well is interesting and could be another clue to find the root cause.

**Comment by leandroalonso** [comment] 2023-11-07 13:45
On the tickets we receive, we have the "PC App Data" that contains a lot of helpful info. It would be good to add play settings there, so we can know if a user has trim silence enabled or not.

In the meantime if a user complains about battery usage can we please ask them if they have trim silence enabled?

**Closed** 2023-12-08 13:37 UTC
Labels: Bug
