### ISSUE TITLE
Latest beta: Homescreen Widget not anymore available

### ISSUE THREAD

**Issue by BKrnk1337** [Automattic/pocket-casts-ios#1162] opened 2023-10-12 08:52 UTC
With the last beta I am not able to use my previously added widgets (they are blank) or add new one.

**Comment by emilylaguna** [comment] 2023-10-18 23:50
I'm not able to reproduce this on my end. Is this still happening for you?

**Comment by azollafox** [comment] 2023-10-24 14:48
I think see a user report of this at 7206205-zen on 7.49

**Comment by joashrajin** [comment] 2023-10-25 10:16
@emilylaguna the user mentioned above says that they removed the widget but do not see it anymore. 

Device info: 

App Version: 7.49
Device: iPhone13,2
OS: 17.0.3

**Comment by emilylaguna** [comment] 2023-10-30 14:25
@joashrajin hmm. Does this happen even after restarting their device? I tried to reproduce but haven't been able to.

**Comment by joashrajin** [comment] 2023-10-31 07:52
@emilylaguna I will ask the user :)

**Comment by leandroalonso** [comment] 2023-12-18 19:25
I'll close this issue. But if it's still happening or if we receive any more reports please feel free to reopen it.

**Closed as completed by leandroalonso** 2023-12-18 19:25 UTC
