### ISSUE TITLE
Notifications Not Working on iPhone 15 Pro

### ISSUE THREAD

**Issue by thabotswana** [Automattic/pocket-casts-ios#1177] opened 2023-10-19 15:11 UTC
### Description

Users with iPhone 15 Pro devices are not receiving notifications, like new episode alerts. However, notifications actually work on these users' other iOS devices. The issue seems to have happened after a device migration. p1696334864850579-slack-C02A333D8LQ

When I have notifications enabled, I should get a notification on my device when Pocket Casts sees there's a new episode.

### Step-by-step reproduction instructions

I'm unable to replicate this

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Report by user in 7176573-zd-a8c

iPhone 15 Pro Max, iOS 17.0.3, Pocket Casts v7.48

**Comment by reginabally** [comment] 2023-10-24 14:02
Another report 7204541-zd-a8c.

What they've tried but didn't help:
* Logging out and back in
* Toggled notifications off and back on
* Restarted phone

App Version: 7.49
Device: iPhone13,4
OS: 16.7.1

**Comment by diyfixtool** [comment] 2023-10-27 09:02
In Settings on your iPhone, choose apps that can send notifications

**Comment by joashrajin** [comment] 2023-11-02 16:02
Duplicate of https://github.com/Automattic/pocket-casts-ios/issues/1198

**Closed as not planned by joashrajin** 2023-11-02 16:02 UTC
Labels: [Type] Bug

**Comment by pachlava** [comment] 2023-12-04 18:49
Changing the resolution to `Close as not planned` instead of `completed`, since this is a duplicate.
