### ISSUE TITLE
Skip Back is not working

### ISSUE THREAD

**Issue by joashrajin** [Automattic/pocket-casts-ios#2141] opened 2024-09-05 10:50 UTC
### Description

We've had a few users mention that skipping back by 15 second increments no longer work on v7.71

### Step-by-step reproduction instructions

1. Set the skip back value to 15 seconds
2. Play an episode and move the progress bar around
3. Let the playback start in the new position
4. Attempt to skip back on an episode

### Screenshots or screen recording

https://github.com/user-attachments/assets/1092e122-db04-400e-8e3c-a8c000de23ef

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

App Version: 7.71
Device: iPhone12,8
OS: 17.6.1

**Comment by joashrajin** [comment] 2024-09-05 10:50
8694489-zd-a8c

**Comment by joashrajin** [comment] 2024-09-05 10:50
8693051-zd-a8c

**Comment by danielebogo** [comment] 2024-09-16 10:28
@joashrajin I'm closing this issue for now. If the issue persists we can re-open it

**Comment by mdrockwell** [comment] 2024-09-18 18:59
> I updated to ver. 7.72 but the skip back problem still exists.

8740156-zd-a8c

**Comment by mdrockwell** [comment] 2024-09-18 19:00
Another case here: 8750557-zd-a8c

**Comment by mdrockwell** [comment] 2024-09-18 19:25
More users reporting the issue here: https://forums.pocketcasts.com/forums/topic/skip-back-button-not-working/

> for the last few days, nothing happens when I click on the skip back button. It is vey annoying.

> I updated both my XS to iOS 18 and PocketCasts to 7.72.0.8 and then noticed that skip back isn’t working.

> Same issue here. I had the problem before the update. I updated it and also iOS and still kept not being able to use it. I have deleted the app couple of times since (all in iOS 18) and still happening after it works for some min.

**Comment by KwisatzJim** [comment] 2024-09-19 06:09
I have the issue as well. Reappeared after upgrading to iOS 18. Seems to happen randomly. Will work at first then at some point during a podcast issue occurs and skip back will continue to not work for some time. Then randomly later in the day it will work again and then stop working later in an episode

**Comment by danielebogo** [comment] 2024-09-19 08:41
@KwisatzJim thanks for the report. 
• Do you use the Trim Silence and/or the Volume Boost?
• Is it happening while you stream an episode? Or after unlocking the device while playing?

It would be great for us to have a record of your full session to understand the exact moment the button stops working.

**Comment by KwisatzJim** [comment] 2024-09-19 08:53
@danielebogo  
I don't use trim silence or volume boost.
I have all my podcasts set to autodownload new episodes, so play them that way.  I've tried skip back from the Watch app, the iPhone lock screen, and within the Pocketcasts app itself.  The issue happens in all of them.  Usually I first try from the Watch app since it's quickest to get to, then when that doesn't work I'll try the lock screen, then the app.

is there a way to get an exact record? or is what I described above what you're looking for?
in looking in the app it says I've saved 9 hours, 10 minutes, 6 seconds using Trim Silence. But it isn't on, so apparently I've used it in the past. I just don't remember. Maybe I used it when I first got the app but later turned it off.
Should I turn those on to test with?  Happy to help out in whatever way I can.

**Comment by danielebogo** [comment] 2024-09-19 09:10
Thanks @KwisatzJim ! I will do some tests with the auto download. Just to be sure, is the button becoming unresponsive while playing? Or is the stream paused?

**Comment by KwisatzJim** [comment] 2024-09-19 09:12
welcome.  only tested while playing.  don't think I've tried while paused.  I'll give it a try next time issue happens

**Comment by danielebogo** [comment] 2024-09-19 09:16
Thanks @KwisatzJim ! I'll do some tests today trying to replicate your scenario

**Comment by scotia70** [comment] 2024-09-19 12:30
FYI it's not just multiples of 15s. My skip back is set to 20s and doesn't work.

**Comment by danielebogo** [comment] 2024-09-19 12:49
@scotia70 could you tell me a bit more about it? I'm trying to understand the exact moment when the button starts to be unresponsive. So far I was only able to reproduce this when the player is paused (with a downloaded episode or with a special effect on)

**Comment by abrain** [comment] 2024-09-19 15:25
When it happens, the button is not totally unresponsive for me. The animation occurs and there is haptic feedback. But the playback continues nonetheless.

I tried to recreate a situation, in which it doesn't work. I waited for increasing amounts of time up to a minute, but it did not reoccur. But then it suddenly did, when the next chapter began.

FYI, I have (on this specific podcast at least) silence trimming on low and 1,3x playback speed. Skip back is 10 seconds.

**Comment by danielebogo** [comment] 2024-09-19 15:38
@abrain always while playing? Or when the stream was paused.

**Comment by wilhuff** [comment] 2024-09-19 16:37
This happens to me as well. Once the back button stops working it does not work when playing or paused. It's almost like the button is disconnected from its action. It animates as normal but its unresponsive when pressed directly in the app or from the watch app.

I have playback speed: 1.3x, trim silence: mad max, volume boost enabled. Changing any of these settings has no effect--the button remains unresponsive. Seeking via the seek bar does work, but afterward the button remains unresponsive.

Force quitting the app and reloading brings the button back into a working state for a bit, but it gets disconnected typically within five minutes. It's almost always broken by the next ad break.

**Comment by abrain** [comment] 2024-09-19 17:02
I only noticed and tested it while playing. But now I can say, when skip back does not work, it also fails while pausing. Hitting play again does not repair it.

The second time around, crossing from chapter to chapter during playback did not break skip-back, probably was a coincidence. It seems to occur within a few minutes, but I cannot make out a specific duration. As mentioned above, it's usually below five minutes.

Until recently, I was able to repair skip-back by moving the progress indicator a bit. But this does not seem to work anymore. Maybe that changed with 7.72. What makes it work again now is selecting a different chapter or playing a different episode.

Also, all my episodes are downloaded.

**Comment by ctubbesing** [comment] 2024-09-23 04:04
I recently updated to version 7.72 thinking this would be fixed but it’s also still happening to me, and I’m able to reliably reproduce it on my device by using the watch app instead of by dragging the progress bar. My steps are:

1. Quit app on phone and on watch
2. Open phone app and resume playing the current podcast. Keep an eye on the phone’s progress bar timestamp for the next step
3. Open the watch app to the player controls screen and press the skip back button (mine is set to -20s). Take note of the episode’s timestamp just before the watch’s skip back button was pressed
4. Let the episode play until it passes the timestamp you had skipped back from previously
5. Try pressing the watch skip back again. It provides haptic feedback but the episode continues playing. The skip back buttons on the phone app and on the iOS Now Playing menu also no longer work

The phone app has to be restarted to fix it. Doing this breaks the skip back button every time for me, so my current workaround has been to to just uninstall the watch app and use the default player on the watch.

I have an iPhone XR on iOS 17.7 and an Apple Watch series 6 on watchOS 10.6.1. My skip back interval is set to 20 seconds, I have volume boost enabled, and trim silence is disabled. All my podcasts are downloaded instead of streamed. I have tested this at 1x speed and 1.5x speed and the issue occurs at both.

**Comment by scotia70** [comment] 2024-09-23 05:10
> @scotia70 could you tell me a bit more about it? I'm trying to understand the exact moment when the button starts to be unresponsive. So far I was only able to reproduce this when the player is paused (with a downloaded episode or with a special effect on)

Hi - I was going to say that I can't reproduce the issue any more.  I first noticed it on my Apple Watch, then when I went to use the phone it also wouldn't skip back; so I killed PC, AirPlayed a podcast to my HP mini, tried to skip back on my Watch, and it failed.  Then on my phone it would also fail to skip back.  Skip back set to 20s.

It's a bugger to reliably reproduce though - after restarting PC it's now working normally.

**Comment by danielebogo** [comment] 2024-09-23 08:50
@ctubbesing thanks for the report. Do you use the player with some effects or did you download the episodes?

**Comment by danielebogo** [comment] 2024-09-23 10:04
> It's a bugger to reliably reproduce though - after restarting PC it's now working normally.

@scotia70 yes. we found another scenario where the skip button doesn't work. But we are still digging into the code to figure out when this happens while playing.

**Comment by KwisatzJim** [comment] 2024-09-23 11:27
I realized I use the Watch app to do the skip back first most of the time so I tried removing it and using the Now Playing, but it just failed to skip back as well.  Happened with a downloaded podcast episode right after the start of it.

**Comment by ctubbesing** [comment] 2024-09-23 12:50
> @ctubbesing thanks for the report. Do you use the player with some effects or did you download the episodes?

When I was recreating the bug the episode was downloaded, playback effects were custom for the podcast, play speed was 1x and 1.5x (it happened at both speeds), trim silence off, volume boost on, skip first and skip last both set to 0s for that podcast

**Comment by danielebogo** [comment] 2024-09-23 19:52
We just released a new beta version where we fixed on of the skip button issues

**Comment by scotia70** [comment] 2024-09-23 23:49
> We just released a new beta version where we fixed on of the skip button issues

How does one get onto the beta programme?

**Comment by danielebogo** [comment] 2024-09-24 10:04
@scotia70 you can contact our support team via support@pocketcasts.com and ask to be added. You can also ask to be added to our Slack Beta if interested

**Comment by mdrockwell** [comment] 2024-09-24 17:15
Another case here: 8762106-zd-a8c

**Comment by mdrockwell** [comment] 2024-09-25 14:47
Another user reporting [in the forums](https://forums.pocketcasts.com/forums/topic/rewind-stopped-working/?view=all#post-5820):

> Sometime last week, the rewind button seems to have stopped working. Forward still works fine, but remind doesn’t from my iphone and watch. Super annoying. I can’t remember if this happened before or after the ios 18 update. I don’t see any complaints in the forum, am I the only one?

**Comment by danielebogo** [comment] 2024-09-25 15:01
@mdrockwell we released 2 fixes in the last 7.73.0.3 beta. Can we ask people in the forum to test it if they have access to it?

**Comment by mdrockwell** [comment] 2024-09-28 20:51
@danielebogo I've reached out to users in the two forum threads where the problem has been reported asking them to give it a try. I also asked them to let us know if they don't have access to the beta and would like to join.

[Thread One](https://forums.pocketcasts.com/forums/topic/rewind-stopped-working/?view=all#post-5933)
[Thread Two](https://forums.pocketcasts.com/forums/topic/skip-back-button-not-working/?view=all#post-5934)

**Comment by danielebogo** [comment] 2024-09-30 15:41
7.73 is out in the App Store. It contains few fixes for the skip back button. I won't close this issue, so feel free to continue reporting here the scenarios where the button is not working

CC @bjtitus

**Closed as completed** 2024-10-10 14:10 UTC
Labels: [Type] Bug, [Priority] High
