### ISSUE TITLE
Up Next: investigate auto add to up next reported issue

### ISSUE THREAD

**Issue by pocketcasts** [Automattic/pocket-casts-ios#40] opened 2022-07-12 16:14 UTC
"Overall, the biggest issue right now is that things aren't being added to the PlaybackQueue/UpNext. I can see in the logs that new episodes were found overnight, and in those podcasts, episodes were even properly archived and removed from the PlaybackQueue. But nothing was added, so no new episodes were queued to download."

Auto add to up next settings:

<img src="https://user-images.githubusercontent.com/610217/129997167-0816665b-8c42-41b4-bf93-712e52017af7.jpeg" width="300">

Log snippet they sent in:
```
2021-08-18 02:06:06 saving played up to 3373.714285714286 for episode Baylor's minor NCAA penalties + important message
2021-08-18 02:06:06 cleanupCurrentPlayer permanent? true
2021-08-18 02:06:10 deactiveAudioSession succeeded
2021-08-18 02:06:12 deactiveAudioSession succeeded
2021-08-18 02:23:18 Background refresh called
2021-08-18 02:23:36 Refresh complete found 4 new episodes
2021-08-18 02:23:37 UpNextSyncTask: Syncing Up Next, sending 0 changes, modified time 1629269396150
2021-08-18 02:23:37 UpNextSyncTask: Server returned not modified to Up Next sync, no changes required
2021-08-18 02:23:40 Received subscription status paid : 0, platform : 3, frequency : 1, giftDays : 0, expiryDate :  2020-10-20 00:00:00 +0000, supporterPodcasts : 0
2021-08-18 02:23:40 Sync succeeded
2021-08-18 02:53:30 Background refresh called
2021-08-18 02:53:56 Background refresh timed out
2021-08-18 03:24:14 Background refresh called
2021-08-18 03:24:18 Failed to clean up custom images from app group: The file "widget_images" couldn't be opened because there is no such file.
2021-08-18 03:24:23 Refresh complete found 4 new episodes
2021-08-18 03:24:25 UpNextSyncTask: Syncing Up Next, sending 0 changes, modified time 1629269396150
2021-08-18 03:24:25 UpNextSyncTask: Server returned not modified to Up Next sync, no changes required
2021-08-18 03:24:28 Received subscription status paid : 0, platform : 3, frequency : 1, giftDays : 0, expiryDate :  2020-10-20 00:00:00 +0000, supporterPodcasts : 0
2021-08-18 03:24:28 Sync succeeded
2021-08-18 03:59:50 Background refresh called
2021-08-18 04:00:16 Background refresh timed out
2021-08-18 04:30:55 Background refresh called
2021-08-18 04:30:59 Failed to clean up custom images from app group: The file "widget_images" couldn't be opened because there is no such file.
2021-08-18 04:31:08 Refresh complete found 5 new episodes
2021-08-18 04:31:12 UpNextSyncTask: Syncing Up Next, sending 0 changes, modified time 1629269396150
2021-08-18 04:31:12 UpNextSyncTask: Server returned not modified to Up Next sync, no changes required
2021-08-18 04:31:15 Received subscription status paid : 0, platform : 3, frequency : 1, giftDays : 0, expiryDate :  2020-10-20 00:00:00 +0000, supporterPodcasts : 0
2021-08-18 04:31:15 Sync succeeded
2021-08-18 05:01:02 Background refresh called
2021-08-18 05:01:28 Background refresh timed out
2021-08-18 05:31:18 Background refresh called
2021-08-18 05:31:23 Failed to clean up custom images from app group: The file "widget_images" couldn't be opened because there is no such file.
2021-08-18 05:31:30 Refresh complete found 8 new episodes
2021-08-18 05:31:31 UpNextSyncTask: Syncing Up Next, sending 0 changes, modified time 1629269396150
2021-08-18 05:31:32 UpNextSyncTask: Server returned not modified to Up Next sync, no changes required
2021-08-18 05:31:35 Received subscription status paid : 0, platform : 3, frequency : 1, giftDays : 0, expiryDate :  2020-10-20 00:00:00 +0000, supporterPodcasts : 0
2021-08-18 05:31:35 Sync succeeded
2021-08-18 06:01:32 Background refresh called
2021-08-18 06:01:34 Archive episode Good news, parents and guardians! Social media might be getting a little safer for kids., fireNotification? false, removeFromPlayer? true
2021-08-18 06:01:58 Background refresh timed out
2021-08-18 06:32:16 Background refresh called
2021-08-18 06:32:21 Failed to clean up custom images from app group: The file "widget_images" couldn't be opened because there is no such file.
2021-08-18 06:32:26 Refresh complete found 2 new episodes
2021-08-18 06:32:29 UpNextSyncTask: Syncing Up Next, sending 0 changes, modified time 1629269396150
2021-08-18 06:32:29 UpNextSyncTask: Server returned not modified to Up Next sync, no changes required
2021-08-18 06:32:33 Received subscription status paid : 0, platform : 3, frequency : 1, giftDays : 0, expiryDate :  2020-10-20 00:00:00 +0000, supporterPodcasts : 0
2021-08-18 06:32:33 Sync succeeded
2021-08-18 07:04:09 Background refresh called
2021-08-18 07:04:35 Background refresh timed out
2021-08-18 07:35:22 Background refresh called
2021-08-18 07:35:27 Failed to clean up custom images from app group: The file "widget_images" couldn't be opened because there is no such file.
2021-08-18 07:35:33 Refresh complete found 3 new episodes
2021-08-18 07:35:35 UpNextSyncTask: Syncing Up Next, sending 0 changes, modified time 1629269396150
2021-08-18 07:35:36 UpNextSyncTask: Server returned not modified to Up Next sync, no changes required
2021-08-18 07:35:38 Received subscription status paid : 0, platform : 3, frequency : 1, giftDays : 0, expiryDate :  2020-10-20 00:00:00 +0000, supporterPodcasts : 0
2021-08-18 07:35:38 Sync succeeded
2021-08-18 08:08:43 Background refresh called
2021-08-18 08:08:45 Archive episode Census shows pandemic's negative economic effect on LGBT community, fireNotification? false, removeFromPlayer? true
2021-08-18 08:08:45 PlaybackQueue: removing Census shows pandemic's negative economic effect on LGBT community episode
2021-08-18 08:08:46 Archive episode Consumer price index shows less inflation. The producer price index shows more. What's happening?, fireNotification? false, removeFromPlayer? true
2021-08-18 08:09:09 Background refresh timed out
2021-08-18 08:39:07 Background refresh called
2021-08-18 08:39:12 Failed to clean up custom images from app group: The file "widget_images" couldn't be opened because there is no such file.
2021-08-18 08:39:18 Refresh complete found 2 new episodes
2021-08-18 08:39:21 UpNextSyncTask: Syncing Up Next, sending 1 changes, modified time 1629269396150
2021-08-18 08:39:22 UpNextSyncTask: server copy matches our copy, nothing action required
2021-08-18 08:39:25 Received subscription status paid : 0, platform : 3, frequency : 1, giftDays : 0, expiryDate :  2020-10-20 00:00:00 +0000, supporterPodcasts : 0
2021-08-18 08:39:25 Sync succeeded
2021-08-18 09:12:57 Background refresh called
2021-08-18 09:13:23 Background refresh timed out
2021-08-18 09:44:21 Background refresh called
2021-08-18 09:44:26 Failed to clean up custom images from app group: The file "widget_images" couldn't be opened because there is no such file.
2021-08-18 09:44:33 Refresh complete found 5 new episodes
2021-08-18 09:44:36 UpNextSyncTask: Syncing Up Next, sending 0 changes, modified time 1629293962009
2021-08-18 09:44:36 UpNextSyncTask: Server returned not modified to Up Next sync, no changes required
2021-08-18 09:44:39 Received subscription status paid : 0, platform : 3, frequency : 1, giftDays : 0, expiryDate :  2020-10-20 00:00:00 +0000, supporterPodcasts : 0
2021-08-18 09:44:39 Sync succeeded
2021-08-18 10:14:22 Background refresh called
2021-08-18 10:14:23 Archive episode Aid for Afghanistan at risk as the Taliban advances rapidly, fireNotification? false, removeFromPlayer? true
2021-08-18 10:14:24 PlaybackQueue: removing Aid for Afghanistan at risk as the Taliban advances rapidly episode
2021-08-18 10:14:48 Background refresh timed out
2021-08-18 10:51:40 Background refresh called
2021-08-18 10:51:45 Failed to clean up custom images from app group: The file "widget_images" couldn't be opened because there is no such file.
2021-08-18 10:51:50 Refresh complete found 3 new episodes
2021-08-18 10:51:53 UpNextSyncTask: Syncing Up Next, sending 1 changes, modified time 1629293962009
2021-08-18 10:51:53 UpNextSyncTask: server copy matches our copy, nothing action required
2021-08-18 10:51:56 Received subscription status paid : 0, platform : 3, frequency : 1, giftDays : 0, expiryDate :  2020-10-20 00:00:00 +0000, supporterPodcasts : 0
2021-08-18 10:51:56 Sync succeeded
```

**Comment by emilylaguna** [comment] 2023-02-03 21:15
I looked into this and was not able to reproduce under normal conditions. However, reviewing the reporting users data at the time they have about 400 podcasts added. 

Unfortunately this cause this issue because the refresh process will exceed the background refresh time limit (which is not very long). 

In order to fix this we will need to reevaluate how the background refresh works and/or change how long the server refresh takes for lots of podcasts. 

I am closing this issue since this is an issue for users with large amounts of podcasts and shouldn't effect the majority of users.

**Closed as completed by emilylaguna** 2023-02-03 21:15 UTC
Labels: [Type] Bug, wontfix, Up Next, [Priority] Low, Auto Add
