### ISSUE TITLE
No Light Mode for the player

### ISSUE THREAD

**Issue by konopielko** [Automattic/pocket-casts-ios#510] opened 2022-11-12 18:11 UTC
### Expected behavior
I expect for the player to be in light mode if I select the light mode in settings

### Actual behavior
The player is always in dark mode

### Steps to reproduce the behavior
Set the device to light mode, play any podcast

**Comment by CookieyedCodes** [comment] 2022-11-13 20:11
From my understanding, it's to match the car os player or something like that +not sure if that's Apple or Android tho+, if this dose get fixed tho make sure it's a setting it should be optional

**Comment by rviljoen** [comment] 2022-11-17 21:34
Looking at the code, it seems like the player screen was designed to be dark on purpose. All themes are either black or use dark colours:

https://github.com/Automattic/pocket-casts-ios/blob/7786534abfbaf48c07d6a7c3d7c1be37deac7a2d/podcasts/ThemeColor.swift#L1655-L1681

There are no comments in the code as to why this is the case. Introducing a light themed player would required some UX designer input.

**Comment by leandroalonso** [comment] 2022-12-15 13:37
Heya @konopielko! Thanks for your request, I'm closing this Issue because feature requests/ideas should go to our  [Discussions](https://github.com/Automattic/pocket-casts-ios/discussions) section! Feel free to create a topic there. :)

**Closed as completed by leandroalonso** 2022-12-15 13:37 UTC
