### ISSUE TITLE
Siri: with "Hey Siri, what's playing?", Siri responds with "This is [episode title] by [day of the week published]."

### ISSUE THREAD

**Issue by pocketcasts** [Automattic/pocket-casts-ios#48] opened 2022-07-12 20:13 UTC
When using "Hey Siri, what's playing?" with Siri, Siri answers with "This is [episode title] by [day of the week published]."

The expected response should be "This is [episode title] by [podcast author]."

### Steps to Reproduce

1. Play an episode
2. Ask Siri, "Hey Siri, what's playing?"
3. Siri will respond with "This is [episode title] by [day of week published]."

### Additional Information

- Reported in #5263803-zen

**Comment by aidano** [comment] 2022-11-12 16:20
This is caused by the Now Playing Info's artist and composer being set – apparently purposely, based on the comment – to the publish date:

https://github.com/Automattic/pocket-casts-ios/blob/cc35d07da4c52cbe4475a2dfddefa4d62d15ce5d/podcasts/NowPlayingHelper.swift#L89

The comment doesn't provide context as to why the date was originally chosen instead of the composer or the Podcast name Perhaps it's an old workaround that is no longer required? 

Also, in case it's not obvious, a fix for this also changes the Now Playing visual content to show the composer or Podcast (arguably a more important fix/improvement?), not just Siri output. On a related note, I think this might be an argument for using the Podcast name, not the author, here.

**Comment by rviljoen** [comment] 2022-11-15 14:20
@aidano I agree, Podcast name is a be a better choice in my opinion.

**Comment by jgcaruso** [comment] 2022-12-13 21:45
@Automattic/pocket-casts-ios I did some digging and it looks like this is the original reason for the date being in the Now Playing section https://github.com/Automattic/pocket-casts-ios-private/issues/2026

> Change now playing info to prioritise the published date of the episode over the author

This looks like it was at a time where both podcast Title and Author were shown in the Now Playing section, but it looks like that has changed in Apple's now playing widget? So we may want to move those details around again so that Podcast title **_and_** Date are shown on screen.

For reference, it was intended to look like this
<img width="793" alt="Screenshot 2022-12-13 at 4 42 13 PM" src="https://user-images.githubusercontent.com/4081020/207450056-76247683-bb9a-41f4-81e0-b904fce215a8.png">


But now looks like this (at least on my device, with a different podcast episode)
![IMG_03178DD5016D-1](https://user-images.githubusercontent.com/4081020/207450013-182c7784-d5e6-407d-9d05-a60296ce9139.jpeg)

But also, given that Siri reads out the wrong thing... maybe we don't want to put the wrong data in the metadata anymore? Or make it a setting?

**Comment by leandroalonso** [comment] 2022-12-14 13:07
@jgcaruso it seems that this new look is only iOS 16+. On iOS 15 I still see the "date - author".

I think we should def change that for iOS 16 at least.

**Comment by rviljoen** [comment] 2022-12-14 13:22
@leandroalonso I assume the _"Hey Siri, what's playing?"_ part of the bug is also present in iOS 15? If yes, then I think it makes sense to fix this across all supported versions.

**Comment by leandroalonso** [comment] 2022-12-14 13:40
@rviljoen My only concern regarding iOS 15 is that this change was originally made to make the Now Playing Widget present more useful information:

| Before | After |
| ------ | ----- |
| ![Image from iOS](https://user-images.githubusercontent.com/610217/74121142-3deaa200-4c16-11ea-86e8-2681a90f7f16.jpg) | ![Image from iOS (1)](https://user-images.githubusercontent.com/610217/74121151-4b079100-4c16-11ea-8a00-8c95377272e0.jpg) |

The percentage of users actively using the widget is way higher than users asking Siri to check what's playing. If the fix to this issue affects the information presented in the widget we need to consider whether this is a good thing or not. :)

**Comment by rviljoen** [comment] 2022-12-14 13:53
@leandroalonso That's a good point. The purist in me wants to set the fields strictly in line with Apple documentation to prevent similar future bugs, but the pragmatist in me likes adding the date to show more useful info to users.

Maybe a middle ground is to build a new string (consisting of the podcast title + separator + date) and then set that as the artist/composer? That we can get the same text on all OS versions and the Siri spoken response will make more sense.

**Comment by jgcaruso** [comment] 2022-12-14 13:59
> Maybe a middle ground is to build a new string (consisting of the podcast title + separator + date) and then set that as the artist/composer? That we can get the same text on all OS versions and the Siri spoken response will make more sense.

I was thinking the same thing too. Having siri read out "Podcast by [Artist] [Date]" should be ok ... unless it says something like "[Artist] _**dash**_ [date]" but thats quick enough to test and find out.

**Comment by jgcaruso** [comment] 2022-12-14 20:53
On iOS 15, the layout appears to be `Artist - Album`. Replacing `Artist` with `[Artist] - [Date]` and `Album` with empty string yields the following (we could also leave `Album` with the podcast title and it'll just duplicate the info in iOS 15.

<img width="2241" alt="Screenshot 2022-12-14 at 3 28 24 PM" src="https://user-images.githubusercontent.com/4081020/207707515-48520988-c89d-409c-a413-e8952be9fbcf.png">

Asking Siri for "what is playing" results in "This is 'A New Formula For Happiness' by 'How to Start Over November 14'" with no "dash" pronounced but also no break or pause between "How to Start Over" and "November 14".

Doing this has an implication on how car infotainment systems (connected over bluetooth, not AirPlay) display the info, where we may want to keep Album title with its value so it fills in all the details as someone may expect

<img width="1389" alt="Screenshot 2022-12-14 at 3 49 18 PM" src="https://user-images.githubusercontent.com/4081020/207710812-3d388c53-26f3-4bc2-a803-418a77559e9e.png">

Previously, the date would have been in that 2nd position. Other car infotainment systems may show different fields in different orders though.

So it seems like if we're going to keep doing weird stuff, we may have to make it weirder to support the iOS 16 layout and make Siri read out useful info for all OSes.

Possibly `[Date] - [Podcast Title]` wherever just Date was being inserted, and be OK with the duplication in the now playing widget for iOS 15 and lower:

"This is 'A New Formula For Happiness' by 'November 14 How to Start Over'"  - sounds weird, but more useful than what we get now.

**Comment by rviljoen** [comment] 2022-12-14 21:31
> So it seems like if we're going to keep doing weird stuff, we may have to make it weirder to support the iOS 16 layout and make Siri read out useful info for all OSes.

I think this is my main concern, that in trying to be useful we end up having to maintain weird hacks for each OS release and/or platform. Looking at the Apple documentation again, my sense is that this is not encouraged :-)

https://developer.apple.com/documentation/mediaplayer/mpnowplayinginfocenter
> You do not have direct control over which information is displayed, or its formatting. You set the values of the now playing info center dictionary according to the information you want to provide to the system. The system, or the connected accessory, handles the information’s display in a consistent manner for all apps.

And other parts may break/are broken which we are not considering here:
> Siri can provide suggestions in search, News, Safari, and other apps using on-device information that you contribute through the NowPlaying API.

We may be teaching Siri that _"November 14"_ is an artist and could see suggestions like _"Play more podcasts from November 14"_ 🙈

**Comment by leandroalonso** [comment] 2022-12-15 20:09
@rviljoen I agree. The downside of keeping the workaround seems bigger than the positive outcome.

@jgcaruso I think we can use it as intended and follow up with the repercussions (if any).

**Closed** 2023-01-20 15:59 UTC
Labels: bug, good first issue, Siri
