### ISSUE TITLE
Show Notes: Not Loading

### ISSUE THREAD

**Issue by joashrajin** [Automattic/pocket-casts-ios#1916] opened 2024-07-16 09:49 UTC
### Description

We've had a single user face an issue where all newer show notes aren't loading for https://pca.st/8LCR. Affecting episode 172 onwards. We were unable to find the root cause of the problem, as we could not reproduce

Internal discussion: p1720786608825129-slack-C02A333D8LQ

### Step-by-step reproduction instructions

We are unable to reproduce

### Screenshots or screen recording

![image](https://github.com/user-attachments/assets/3d0c3979-7bd8-4ee2-91f1-6cac790594c9)
![image](https://github.com/user-attachments/assets/0863cb1d-7a6f-4c56-ad8f-500cc1460ce1)
![image](https://github.com/user-attachments/assets/b00fa86f-f0b5-4a8f-9fb5-c105b84e62d5)

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

App Version: 7.68
Device: iPhone16,2
OS: 17.5.1

**Comment by BKrnk1337** [comment] 2024-07-19 08:58
It was me that reported that behaviour. I found another podcast with the same behaviour and I was told to add it here:


https://pca.st/podcast/c8d33300-d312-0131-32b7-723c91aeae46

The last shownotes that are loading are in the Episode 236. All episodes after are not displaying the show notes.

![image](https://github.com/user-attachments/assets/68a6e75e-ca6f-4425-b47a-bbcfc7dd1a16)

**Comment by BKrnk1337** [comment] 2024-07-22 06:12
And another one:

https://pca.st/episode/5120ccff-5a9d-4375-8024-d32084ff8207

This time just the current episode

**Comment by igotdes** [comment] 2024-07-23 04:28
Also reported in #8476610-zen for this podcast: https://pca.st/E3n6

**Comment by leandroalonso** [comment] 2024-07-23 14:22
Should be fixed by #1928

**Closed as completed by leandroalonso** 2024-07-23 14:22 UTC

**Comment by BKrnk1337** [comment] 2024-07-23 16:44
> Should be fixed by #1928

If the new version is available, I will test it extensively. I’m glad you found the cause of the problem.

**Comment by leandroalonso** [comment] 2024-07-23 17:12
@BKrnk1337 it should be available on `7.69.0.1`. Please let me know if it happens again!
